### ISSUE TITLE
Poll mode: Multiple

### ISSUE THREAD

**Issue by zendobk** [yellowme/slack-poll#14]
Currently, when I create a poll, its mode is Single as default. How can I create a poll with mode: Multiple?

**Comment by zendobk** [comment]
I've just found the options in source code but not in the docs (readme.md). Can I create a PR or you will update the docs? Thanks!

**Comment by rejonpardenilla** [comment]
Hey @zendobk, you can use the `-m` option to make it multiple. And yes, any PRs are welcome.
